server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:posheve.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: posheve
    trust-store: classpath:posheve.p12
    trust-store-password: password
spring:
  application:
    name: TlgBot
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    database: postgresql
  liquibase:
    change-log: classpath:/db/liquibase/changelog-master.xml
    enabled: true

#custom config properties section
tlgbot:
  webhook:
    url: ${WEBHOOK_URL}
  bot:
    token: ${BOT_TOKEN}
  excel:
    dir: generated-files